### ISSUE TITLE
Expose stomp.ConnectionListener on_disconnected() method

### ISSUE THREAD

**Issue by shahha** [snuids/amqstompclient#1]
We are using amqstompclient for our worker/listener in a kube pod which listens to activemq queue continuously. Due to some reason at a random time listener just stops listening to queue without any error. Last message we can see in log is Receiver loop ended. I have a feeling we need to do workaround which is mentioned in this link, http://jasonrbriggs.github.io/stomp.py/api.html#dealing-with-disconnects. Problem is stomp.ConnectionListener's on_disconnected() method is not exposed in AMQListener class and this listener is hardcoded. 
I propose adding a new listener class which can reconnect gracefully on disconnects by using workaround mention above and also allow passing different type of listener to AMQClient.
I will try to put a PR for this.

**Comment by snuids** [comment]
Done.
Can you confirm that it is working for you ?

Thx,
