### ISSUE TITLE
Tag pas changé donc version n'est pas dispo dans Pypi

### ISSUE THREAD

**Issue by julianf19** [snuids/amqstompclient#5]
Salut,
Comment vas-tu?
C'est mon premier pr sur un package donc je ne sais pas trop ce que je fais.
J'ai oublié de changer le numéro de tag du coup dans Pypi la nouvelle version n'est pas dispo

Tu pourrais la changer stp?

Merci

**Comment by snuids** [comment]
Pour le package, je dois bosser un peu de mon côté. J'essaye de te faire ça quand j'ai le temps. PyPI n'est pas lié en direct avec GitHub

**Comment by snuids** [comment]
Et voilà c'est fait
https://pypi.org/project/amqstompclient/

**Comment by julianf19** [comment]
Merciii beaucoup
